name: "ESLint-score"
description: "This Github Action generates ESLint Score for your JavaScript codebase"
branding:
  icon: "at-sign"
  color: "gray-dark"
inputs:
  start-point:
    description: "enter the starting point"
    required: true
    default: "./"
outputs:
  score: # output will be available to future steps
    description: "Score base on your code base"
runs:
  using: "node16"
  main: "dist/index.js"
