name: "ESLint-score"
description: "This Github Action generates ESLint Score for your JavaScript codebase"
branding:
  icon: "at-sign"
  color: "gray-dark"
inputs:
  action:
    description: "Name the action you want to run. options SETUP/SCORE"
    required: true
  start-point:
    description: "Enter the starting point"
    required: true
    default: "./"
outputs:
  setup:
    description: "setting up everything to run"
  score: # output will be available to future steps
    description: "Score base on your code base"
runs:
  using: "node16"
  main: "dist/index.js"
